language: python
python:
  - "2.7"
  - "3.6"

before_install: "pip install -r requirements.txt"

script:

  # Para ejecutar pruebas del examen versión A:
  #- "python -m coverage run Version_A/test_A.py"
  
  # Para ejecutar pruebas del examen versión B:
  - "python -m coverage run Version_B/test_B.py"

after_script: "coveralls"